#!/usr/bin/env bash
# Configure my domain zone:
# www --> 47032-lb-01 54.144.45.150
# web-01 --> 47032-web-01 100.26.171.10
# web-02 --> 47032-web-02 52.3.251.124	

display_info ()
{
    domain="$1"
    subdomain="$2"
    dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$subdomain"
}

for subdomain in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$subdomain" ] ;
    then
	display_info "$1" "$subdomain"
    fi
done
