#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend dylanwaithaka.tech
    timeout client  30000
    bind 0:80
    default_backend dylanwaithaka.tech_backend

backend dylanwaithaka.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 341617-web-01 100.26.171.10:80 check
    server 341617-web-02 52.3.251.124:80 check
EOT

sudo service haproxy restart
